Service name prefix
Zooz/prometheus-api-metrics pull request #11
Opened 2018-11-01 16:22 UTC by idanto

- Add ability to add a prefix to metrics names (custom or project name)
- Add the ability to exclude routes from being collected
- Improve code coverage
- Add request.js HTTP calls duration collector

2018-11-06 08:19 UTC, ugolas requested changes

2018-11-06 08:19 UTC, ugolas commented on README.md
> +- excludeRoutes - Array of routes to exclude. Routes sould be in your framework syntax
```suggestion
- excludeRoutes - Array of routes to exclude. Routes should be in your framework syntax.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +1. If you pass to the middleware the `metricsPath` option the path will be the one the you choosed.
```suggestion
1. If you pass to the middleware the `metricsPath` option the path will be the one that you chose.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +2. If you are using express framework and no route was found for the request (e.g: 404 status code), the request will not be collected. that's because we'll risk in a memory leak since the route is n
```suggestion
2. If you are using express framework and no route was found for the request (e.g: 404 status code), the request will not be collected. that's because we'll risk memory leak since the route is not a pattern but a hardcoded string.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +This feature enbale you to easily process the result of Request.js timings feature.
```suggestion
This feature enbales you to easily process the result of Request.js timings feature.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +- countClientErrors - Boolean that indicates if to collect client errors as Counter, this counter will have target and error code labels.
```suggestion
- countClientErrors - Boolean that indicates whether to collect client errors as Counter, this counter will have target and error code labels.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +- prefix - A custom matrics names prefix, the package will add underscode between your prefix to the metric name.
```suggestion
- prefix - A custom metrics names prefix, the package will add underscore between your prefix to the metric name.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +- metricsPrefix - A custom matrics names prefix, the package will add underscode between your prefix to the metric name.
```suggestion
- metricsPrefix - A custom metrics names prefix, the package will add underscore between your prefix to the metric name.
```

2018-11-06 08:19 UTC, ugolas commented on README.md
> +2. Override - you can override the `route` and `target` attribute instead of taking them from the request object. In order to do that you should set a `metrics` object on your request with those attr
```suggestion
2. Override - you can override the `route` and `target` attributes instead of taking them from the request object. In order to do that you should set a `metrics` object on your request with those attribute:
```

2018-11-06 08:19 UTC, ugolas commented on src/metrics-middleware.js
> +function _getMetricNames(metricsPrefix) {
I would move this method to a utils.js file or something

2018-11-06 08:19 UTC, ugolas commented on src/metrics-middleware.js
> +function _shouldLogMetrics(excludeRoutes, route) {
I would also put it in utils.js file, easier to test these utility methods, and the main file is leaner.

2018-11-06 08:19 UTC, ugolas commented on src/request-response-collector.js
> +        let metricsPrefix = useUniqueHistogramName === true ? projectName : prefix;
this logic seems the same as the one in the middleware - maybe think of a way to share it?

2018-11-06 08:19 UTC, ugolas commented on src/request-response-collector.js
> +    require('pkginfo')(metricsMiddleware, { dir: Path.dirname(module.parent.filename), include: ['name'] });
why is the require here and not in the top of the file?

2018-11-06 08:19 UTC, ugolas commented on README.md
> +
I think you are missing examples of initialising the packages explicitly with `init()` & `collect()` vs `new MetricsCollector(...)`, and explain when you should can use the latter. or maybe i missed it!

2018-11-06 08:19 UTC, ugolas commented on test/unit-test/metric-middleware-test.js
> +    describe.skip('override the default path', () => {
why is it skipped?

2018-11-06 08:44 UTC, idanto commented on src/request-response-collector.js
> +    require('pkginfo')(metricsMiddleware, { dir: Path.dirname(module.parent.filename), include: ['name'] });
because I want to get the parent package.json and in the root I can't

2018-11-06 19:38 UTC, idanto commented on src/request-response-collector.js
> +        let metricsPrefix = useUniqueHistogramName === true ? projectName : prefix;
done, added to utils

2018-11-06 19:47 UTC, idanto commented on test/unit-test/metric-middleware-test.js
> +    describe.skip('override the default path', () => {
fixed

2018-11-07 08:05 UTC, ugolas submitted a review, later dismissed

2018-11-07 11:03 UTC, merged